### ISSUE TITLE
budget.sec.gouv.sn

### ISSUE THREAD

**Issue by boubakarforseti** [senegalouvert/annuaire-sites-publics-senegal#29]
## Nom du site

(Direction Generale du Budget)

## URL du site

(https://budget.sec.gouv.sn)

## Type de site

(Direction d'un Ministère.)

## Commentaires supplémentaires

(Sous l'autorité du Directeur général du Budget, la Direction générale du Budget est chargée:
de l'élaboration des projets de lois de finances;
du contrôle général de l'emploi des crédits budgétaires et de l'exécution des recettes du budget de l'Etat;
du pilotage des réformes budgétaires ainsi que de l'élaboration de la stratégie pluriannuelle des finances publiques, en collaboration avec les services compétents de l'Etat;
de la centralisation de la programmation budgétaire des projets et programmes d'investissements publics élaborés par les ministères et organismes intéressés ainsi que de la recherche de financements nécessaires à  leur réalisation ; ,
de la répartition, sous l'autorité du ministre chargé des Finances, des enveloppes indicatives de crédits budgétaires entre les départements ministériels et les institutions constitutionnelles;
de la gestion des relations de coopération financière avec les collectivités et organismes publies ou privés étrangers ou internationaux;
de l'étude préalable de tous projets d'actes législatifs ou réglementaires ayant une incidence sur le budget de l'Etat;
de la concession et de la liquidation des pensions civiles et militaires de retraite ainsi que des rentes viagères;
de l'acquisition, pour les institutions et autres structures administratives, de matériel et mobilier de bureau, de mobilier d'appartement et de véhicules administratifs;
de la centralisation de la comptabilité des matières des administrations publiques;
de la gestion des formalités de douane, de transport et de magasinage du matériel appartenant à  l'Etat;
de l'administration des systèmes d'information de gestion des dépenses publiques.

Le Directeur général du Budget est assisté dans ses fonctions par un Coordonnateur nommé par décret.
Le Directeur général du Budget peut, également, disposer de conseillers techniques nommés par arrêté du Ministre chargé des Finances.

La Direction générale du Budget comprend:
la Cellule de Suivi et de Synthèse;
la Cellule des Etudes et de la Réglementation;
la Direction du Contrôle interne;
la Direction de l'Administration et du Personnel;
la Direction des Systèmes d'Information;
la Direction de la Programmation budgétaire;
la Direction de la Coopération et des Financements extérieurs ;
la Direction de la Solde;
la Direction des Pensions;
la Direction du Contrôle budgétaire;
la Direction du Matériel et du Transit administratif.)

**Comment by dofbi** [comment]
Hello @boubakarforseti 
Merci pour la contribution 🇸🇳 👍🏾
