### ISSUE TITLE
[Nouveau Site]

### ISSUE THREAD

**Issue by boubakarforseti** [senegalouvert/annuaire-sites-publics-senegal#39]
## Nom du site

(Commission de Regulation du Secteur de l'Energie (CRSE))

## URL du site

(https://www.crse.sn/)

## Type de site

( Services de Regulation)

## Commentaires supplémentaires

(Instituée par la loi n° 98-29 du 14 avril 1998, la Commission de Régulation du Secteur de l’Electricité est une autorité indépendante chargée de la régulation des activités de production, de transport, de distribution et de vente d’énergie électrique sur toute l’étendue du territoire national.

Missions :

promouvoir le développement rationnel de l’offre d’énergie électrique ;
veiller à l’équilibre économique financier du secteur de l’électricité et de la préservation des conditions économiques nécessaires à sa viabilité :
veiller à la préservation des intérêts des consommateurs et à assurer la protection de leurs droits pour ce qui concerne le prix, la fourniture et la qualité de l’énergie électrique ;
promouvoir la concurrence et la participation du secteur privé en matière de production, de transport, de distribution et de vente d’énergie électrique : et
assurer les conditions de viabilité financière des entreprises du secteur de l’électricité.
Elle a des attributions décisionnelles et des attributions consultatives.

Composition :

3 membres nommés par décret :

1 Président
2 Commissaires
Ces membres sont choisis en raison de leur qualification dans les domaines juridique, technique et économique et de leur expertise dans le secteur de l’électricité.)

**Comment by dofbi** [comment]
Bonjour @boubakarforseti 🎉 
Merci pour votre contribution 👍🏾 🇸🇳
