### ISSUE TITLE
[Erreur] ADIE e-Working conference

### ISSUE THREAD

**Issue by abdoulsn** [senegalouvert/annuaire-sites-publics-senegal#45]
## Nom du site

ADIE e-Working

## URL du site

conference.sec.gouv.sn

## Description de l'erreur

Le siteweb semble etre inexistant ou mal renseigné, j'ai trouvé cette url doté de port  nommé SENUM e-Working  
https://conference2.sec.gouv.sn:8443/

**Comment by dofbi** [comment]
Fixe #49
