### ISSUE TITLE
[Error] url mdiabete

### ISSUE THREAD

**Issue by abdoulsn** [senegalouvert/annuaire-sites-publics-senegal#48]
## Nom du site

(Insérez le nom du site ici)

## URL du site

(Insérez l'URL du site ici)

## Description de l'erreur

Duplicated and not working website:  
https://github.com/senegalouvert/annuaire-sites-publics-senegal/blob/b80c3924c86a11e7762ab35582d276feaff79914/data/annuaire.csv#L111    
https://github.com/senegalouvert/annuaire-sites-publics-senegal/blob/b80c3924c86a11e7762ab35582d276feaff79914/data/annuaire.csv#L112  

Correct one is : https://mdiabete.gouv.sn

**Comment by dofbi** [comment]
Fixe #49
